# Generated by Django 4.2.6 on 2023-10-13 19:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("listings", "0002_band_active_band_biography_band_genre_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="band",
            name="genre",
            field=models.CharField(
                choices=[("HH", "Hip Hop"), ("SP", "Synth Pop"), ("AR", "Alternative")],
                max_length=5,
            ),
        ),
    ]
