# Generated by Django 4.2.6 on 2023-10-13 21:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("listings", "0005_listing_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listing",
            name="title",
            field=models.CharField(max_length=50),
        ),
    ]
